[build]
  command = "chmod +x netlify.sh && ./netlify.sh"
  publish = "dist"

# Handle React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable handling
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 