[build]
  command = "npm run build"
  publish = "dist"

# Handle React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable handling
[build.environment]
  NODE_VERSION = "18" 